[idgenms]
host="http://localhost"
port=3001

[database-clustermgt-ms]
host="http://localhost"
port=3002

[productmgms]
host="http://localhost"
port=3003

[usermgtms]
host="http://localhost"
port=3004

[ordermgtms]
host="http://localhost"
port=3005

